### ISSUE TITLE
can not import 'react-calendar-datetime-picker/dist/index.css'

### ISSUE THREAD

**Issue by mahyaa21** [mmehdinasiri/react-calendar-datetime-picker#7]
Hello, I can not import 'react-calendar-datetime-picker/dist/index.css'. I have an error about loader in my nextjs project please help me !

**Comment by mmehdinasiri** [comment]
Your problem is related to the built file format that we used modern js but in the new version that released a few hours ago(version 1.4.2), we replace it with cjs.
