### ISSUE TITLE
Vanilla JS

### ISSUE THREAD

**Issue by MR-Mostafa** [mmehdinasiri/react-calendar-datetime-picker#8]
Hi,
Is there any version of this library that does not have the ReactJS dependency? (Just use vanilla Js)

If not:
1- Do you have a plan to do this?
2- Do you have a vanilla date range picker that does not any dependency (like jquery or react and etc)? (another library)

Thanks.

**Comment by mmehdinasiri** [comment]
Hi Mostafa,
Unfortunately no there isn't.
Currently, I don't have enough time to implement a date picker with Vanilla js, at least in a short time. 
And I don't know any Persian date picker without any dependency.
Maybe this [lib ](http://babakhani.github.io/PersianWebToolkit/beta/) can be helpful for you but I don't know, does it support selecting a range of dates or not and I think you need jquery.
